### ISSUE TITLE
Satisfying sound when you drop a letter

### ISSUE THREAD

**Issue by colinperepelken** [caitlin-hutnyk/qlessonline#6]
Like a nice solid metallic or wooden "click" as a letter clicks into place.
Perhaps a happy ding after validation once you get a solution.

**Comment by xXjasonmillerXx** [comment]
dubstep drop when you win

**Comment by colinperepelken** [comment]
[mixkit-plastic-bubble-click-1124.wav.zip](https://github.com/caitlin-hutnyk/qlessonline/files/7961814/mixkit-plastic-bubble-click-1124.wav.zip) Maybe this?

**Comment by colinperepelken** [comment]
[mixkit-cool-interface-click-tone-2568.wav.zip](https://github.com/caitlin-hutnyk/qlessonline/files/7961819/mixkit-cool-interface-click-tone-2568.wav.zip) Actually this is pretty good!

**Comment by colinperepelken** [comment]
https://stackoverflow.com/questions/9419263/how-to-play-audio

**Comment by caitlin-hutnyk** [comment]
ok i tried to do this and it was a pain in the ass with webpack, so if you want to do it you have to make a pr @colinperepelken
